### ISSUE TITLE
create (optional) locking to not to parallel backups on the same machine

### ISSUE THREAD

**Issue by darktim** [ungleich/ccollect#1]
Hi Nico

if a Backup takes longer than 24 hours (which may occour on slow machines during initial backup), ccollect will not refuse to start another backup job for that target.

I would like to have a possibillitiy of locking for the targets. 

For example you could use the marker file to determine of a backup is active for this target (if the pid is stale, you can start a new one, of course ;)

Greetz,
Andre

**Comment by pazifi** [comment]
Hi Andre,
i know it is not the same, but you can use "lockrun" or  "flock" in crontab.

Example:
flock -xn /tmp/backup1.lck /opt/ccollect-something

Greetings
zap

**Comment by darktim** [comment]
Uhh, a reply to a 5 year old issue ;)

Fortunately I am not working for the company where we used ccollect anymore, but thanks anyways.

**Comment by darko-poljak** [comment]
Closing this stale issue.
